# Debug level
debug: INFO

# Language (en, fr)
locale: en

# Server name or MultiLobby group name on which cracked players are redirected for register/login them.
authServer: crack

# Backend Configuration
backend:
  # Driver for SQLite (org.sqlite.JDBC), MySQL (com.mysql.jdbc.Driver) or MariaDB (org.mariadb.jdbc.Driver)
  # If you want to use SQLite, you need to install the driver yourself
  # Easy way : https://www.spigotmc.org/resources/sqlite-for-bungeecord.57191/
  # Hard way : https://gist.github.com/games647/d2a57abf90f707c0bd1107e432c580f3
  driver: 'com.mysql.jdbc.Driver'
  # Database host address
  host: '127.0.0.1'
  # Database port
  port: '3306'
  # Username about Database Connection Infos
  user: username
  # Password about Database Connection Infos
  password: password
  # Database Name, use with converters or as SQLITE database name
  database: database
  # Table name
  table: premium
  # If connection should use SSL
  useSSL: true
  
# Allow cracked player to use premium username
secondAttempt: true

# Block player to switch server until they are logged in
blockServerSwitch: true

# Time to confirm /premium command
timeToConfirm: 30

# Should the plugin set the real UUID for Premium players ?
fixUUID: true

# Use it with precaution ! All players connecting from this address won't need authentification. Use this to register your Geyser proxy addresses such as 127.0.0.1 or 172.18.0.* (You can use wildcard matching).
geyserProxy: []